# Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
        - name: app
          image: tihlok/player-service:latest
          ports:
            - containerPort: 29001
          imagePullPolicy: Always
# Deployment YAML definition
---
# Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: player-service
spec:
  selector:
    app: player-service
  ports:
    - port: 29001
      targetPort: 29001
  type: LoadBalancer
# Service YAML definition
